import test from 'node:test';import assert from 'node:assert/strict';
import {Astra,TOOLS} from '../server/astra.ts';import {initialGame,start,tick} from '../game/engine.ts';
function setup(){const g=initialGame('live');start(g);const sent:Array<Record<string,unknown>>=[];let closed=false;const a=new Astra(g,{send:s=>sent.push(JSON.parse(s)),close:()=>{closed=true;}},()=>{});a.start();return {g,a,sent,closed:()=>closed};}
test('native diagnostic definition is async and preserves original call id',()=>{assert.equal(TOOLS.find(t=>t.name==='run_diagnostic')?.async,true);const {g,a,sent}=setup();a.receive({type:'response.created',response:{id:'r1'}});a.receive({type:'response.output_item.done',item:{type:'function_call',name:'run_diagnostic',call_id:'diag-1',arguments:'{"building":"lifeSupport"}'}});a.receive({type:'response.completed',response:{id:'r1'}});assert.equal(sent.length,1);for(let i=0;i<8;i++)a.completed(tick(g));const input=sent.at(-1)!.input as Array<{type:string;call_id?:string}>;assert.ok(input.some(i=>i.type==='function_call_output'&&i.call_id==='diag-1'));});
test('steering targets active response and waits for automatic successor',()=>{const {a,sent}=setup();a.receive({type:'response.created',response:{id:'r1'}});a.wake('Dust storm');assert.equal(sent.at(-1)!.type,'response.steer');assert.equal(sent.at(-1)!.previous_response_id,'r1');a.receive({type:'response.steer.accepted'});a.receive({type:'response.incomplete',response:{id:'r1',incomplete_details:{reason:'steered'}}});assert.equal(sent.length,2);a.receive({type:'response.created',response:{id:'r2'}});a.wake('Oxygen failure');assert.equal(sent.at(-1)!.previous_response_id,'r2');});
test('pending steering returns required results without repeating the accepted instruction',()=>{const {a,sent}=setup();a.receive({type:'response.created',response:{id:'r1'}});a.wake('Hull damage');a.receive({type:'response.output_item.done',item:{type:'function_call',name:'get_colony_status',call_id:'status-1',arguments:'{}'}});a.receive({type:'response.completed',response:{id:'r1'}});assert.equal(sent.length,2);a.receive({type:'response.steer.pending',steer:{previous_response_id:'r1'},required_input:[{call_id:'status-1'}]});assert.equal(sent.length,3);assert.equal(sent[2].type,'response.create');assert.equal(sent[2].previous_response_id,'r1');});
test('effort configuration is inserted at an explicit response boundary',()=>{const {a,g,sent}=setup();a.receive({type:'response.created',response:{id:'r1'}});g.pendingEffort='high';a.receive({type:'response.completed',response:{id:'r1'}});a.wake('Critical oxygen');const request=sent.at(-1)!;assert.deepEqual(request.reasoning,{effort:'low'});assert.deepEqual((request.input as unknown[])[0],{type:'configuration_update',reasoning:{effort:'high'}});assert.equal(g.effort,'high');assert.equal(g.pendingEffort,null);});
test('duplicate function events cannot spend supplies twice; malformed args are rejected',()=>{const {a,g}=setup();const item={type:'function_call',name:'release_oxygen',call_id:'o1',arguments:'{}'};a.receive({type:'response.output_item.done',item});a.receive({type:'response.output_item.done',item});assert.equal(g.canisters,1);a.receive({type:'response.output_item.done',item:{...item,call_id:'o2',arguments:'{"extra":true}'}});assert.equal(g.canisters,1);});
test('API failure preserves telemetry and stops live actions',()=>{const {a,g,closed}=setup();a.receive({type:'error'});assert.equal(g.phase,'interrupted');assert.equal(g.population,42);assert.equal(closed(),true);});

test('API evidence is based on received IDs and reported usage, never invented',()=>{
 const {a,g}=setup();assert.equal(g.apiReceipts.length,0);
 a.receive({type:'response.created',response:{id:'actual-response-1'}});
 assert.equal(g.apiReceipts[0].reportedEffort,null);assert.equal(g.apiReceipts[0].reasoningTokens,null);
 a.receive({type:'response.output_item.done',item:{type:'function_call',name:'release_oxygen',call_id:'measured-tool',arguments:'{}'}});
 assert.equal(g.evidence[0].responseId,'actual-response-1');
 a.receive({type:'response.completed',response:{id:'actual-response-1',reasoning:{effort:'high'},usage:{total_tokens:210,output_tokens_details:{reasoning_tokens:90}}}});
 assert.equal(g.apiReceipts[0].reportedEffort,'high');assert.equal(g.apiReceipts[0].reasoningTokens,90);assert.equal(g.apiReceipts[0].totalTokens,210);assert.equal(g.apiReceipts[0].status,'completed');
});
