"use client";
import { useMemo, useState } from 'react';
import { useMission } from './use-mission';
import { eligible, LABELS, SCENARIOS, flows, unattendedReplay, desiredEffort } from '@/game/engine';
import type { Building, Resource, ScenarioId } from '@/game/engine';
import { ArrowRight, Download, Crosshair, Droplets, Heart, Leaf, Pause, Play, Radio, RotateCcw, Shuffle, Sparkles, Users, Wind, Wrench, X, Zap } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Progress } from '@/components/ui/progress';
import { Dialog, DialogContent, DialogDescription, DialogTitle } from '@/components/ui/dialog';

const sites:{id:Building;x:number;y:number;icon:typeof Wind}[]=[
 {id:'solar',x:26.7,y:57,icon:Zap},{id:'habitat',x:50.4,y:22.8,icon:Users},
 {id:'lifeSupport',x:27.3,y:33.1,icon:Wind},{id:'greenhouse',x:75.2,y:35,icon:Leaf},{id:'recycler',x:66.8,y:55.2,icon:Droplets},
];
const reserves:{id:Resource;label:string;icon:typeof Wind}[]=[{id:'oxygen',label:'Oxygen',icon:Wind},{id:'power',label:'Power',icon:Zap},{id:'water',label:'Water',icon:Droplets},{id:'food',label:'Food',icon:Leaf},{id:'stability',label:'Stability',icon:Heart}];
const chaosIcons={dust:Wind,oxygen:Wind,hull:Crosshair,battery:Zap,water:Droplets,food:Leaf};
const names={dust:'Dust wall',oxygen:'Air failure',hull:'Meteor strike',battery:'Blackout',water:'Water crisis',food:'Alien blight'};

export default function Home(){
 const {game:g,paused,pause,liveAvailable,connecting,parsing,notice,setNotice,begin,inject,random,text,reset,report}=useMission();
 const baseline=useMemo(()=>unattendedReplay(g),[g]);const rates=flows(g);const activeCrews=g.jobs.filter(j=>j.type==='repair');
 const exportReport=()=>{const file=new Blob([JSON.stringify({operator:g.mode==='live'?'Live GPT-6 Astra':'Scripted rehearsal; no model calls',tick:g.tick,survivors:g.population,resources:g.resources,supplies:{parts:g.parts,oxygenCanisters:g.canisters,crewsBusy:activeCrews.length},disasters:g.disasters,actions:g.evidence,apiResponses:g.apiReceipts,unattendedReplay:baseline,comparisonNote:'Counterfactual inside the game rules, using the same accepted disasters and no operator actions.'},null,2)],{type:'application/json'});const url=URL.createObjectURL(file),link=document.createElement('a');link.href=url;link.download='last-light-round-report.json';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const [composer,setComposer]=useState(false),[target,setTarget]=useState<Building|null>(null),[selection,setSelection]=useState<ScenarioId|'random'|'custom'>('random');
 const [draft,setDraft]=useState(''),[busy,setBusy]=useState(false),[composerError,setComposerError]=useState(''),[showLog,setShowLog]=useState(false);
 const running=g.phase==='running',finished=['won','lost','interrupted'].includes(g.phase),cooldown=Math.max(0,12-(g.tick-g.lastChaos)),remaining=Math.max(0,180-g.tick);
 const resetAll=()=>{reset();setComposer(false);setDraft('');setBusy(false);setComposerError('');};
 const openChaos=async(building:Building|null=null,scenario:ScenarioId|'random'|'custom'='random')=>{
  if(!running||busy)return;setBusy(true);setComposerError('');setTarget(building);setSelection(scenario);
  try{await pause(true);setComposer(true);}catch(error){report(error);}finally{setBusy(false);}
 };
 const closeChaos=async()=>{if(busy)return;if(!running){setComposer(false);return;}setBusy(true);try{await pause(false);setComposer(false);setComposerError('');}catch(error){setComposerError(error instanceof Error?error.message:'Could not resume.');}finally{setBusy(false);}};
 const unleash=async()=>{setBusy(true);setComposerError('');try{if(selection==='custom')await text(draft);else if(selection==='random')await random();else await inject(selection);await pause(false);setComposer(false);setDraft('');}catch(error){setComposerError(error instanceof Error?error.message:'Could not apply this disaster.');}finally{setBusy(false);}};
 const chosen=SCENARIOS.find(s=>s.id===selection);
 const unavailable=selection==='random'?(SCENARIOS.some(s=>!eligible(g,s.id))?null:'Wait for the next chaos charge.'):selection==='custom'?(cooldown?`Next chaos charge in ${cooldown}s. Resume time to recharge.`:!draft.trim()?'Describe your disaster first.':null):eligible(g,selection);
 const lastChaos=g.log.filter(l=>l.kind==='chaos').at(-1);
 return <main className="game-shell">
  <header className="game-header"><a href="/" className="wordmark">LAST LIGHT<span>MARS SURVIVAL</span></a><div className={`rescue-clock ${paused?'clock-paused':''}`}><span>{paused?<><Pause size={12}/> TIME PAUSED</>:'RESCUE IN'}</span><strong>{Math.floor(remaining/60)}:{String(remaining%60).padStart(2,'0')}</strong></div><div className="crew-count"><Users size={18}/><strong>{g.population}<small> / 42</small></strong><span>STILL HERE</span></div></header>
  <section className="world" aria-label="Interactive Mars colony">
   <div className="world-surface">
    <img className="planet-art" src="/mars-colony.png" alt="A small colony of habitats, solar panels, a greenhouse, life support tanks, and a water recycler on the rust-red surface of Mars." width="1536" height="1024" fetchPriority="high"/>
    <div className="scene-shade"/>
    <div className="location-stamp">UTOPIA PLANITIA <span>38.4° N · SOL 187</span></div>
    <div className="world-controls"><span className="mode-label"><i/>{g.mode==='live'?'LIVE ASTRA':'FREE REHEARSAL'}</span><button onClick={resetAll} aria-label="Restart mission" title="Restart mission"><RotateCcw size={16}/></button></div>
    {sites.map(b=>{const health=g.health[b.id],jobs=g.jobs.filter(j=>j.building===b.id),crisis=g.crises.find(c=>c.building===b.id),damaged=health<80||!!crisis;return <button key={b.id} className={`site-target ${damaged?'site-danger':''} ${jobs.length?'site-working':''}`} style={{left:`${b.x}%`,top:`${b.y}%`}} disabled={!running||busy} onClick={()=>{void openChaos(b.id,SCENARIOS.find(s=>s.building===b.id)!.id)}} aria-label={`Target ${LABELS[b.id]}, ${health}% integrity${jobs.length?', operations in progress':''}`}>
     <span className="target-ring"><b.icon size={19}/><Crosshair size={24} className="target-crosshair"/></span><span className="target-caption"><strong>{LABELS[b.id]}</strong><small>{jobs.length?<><Wrench size={11}/>{jobs[0].type==='repair'?'Repair':'Scan'} · {jobs[0].due-g.tick}s</>:crisis?crisis.title:`${health}% integrity`}</small><span className="target-health"><i style={{width:`${health}%`}}/></span></span>
    </button>})}
    {running&&<div className={`scene-instruction ${paused?'is-paused':''}`}>{paused?<><Pause size={15}/> The colony is holding its breath.</>:<><Crosshair size={16}/>{g.resources.oxygen<=15?`Oxygen critical · next loss in ${6-g.oxygenHazard}s`:cooldown?`Chaos recharging · ${cooldown}s`:'Pick a building. Make something go wrong.'}</>}</div>}
    {!running&&<div className="brief-wrap"><div className="mission-brief"><span className="chapter">{finished?'THE AFTERMATH':'YOU ARE THE CHAOS'}</span><h1>{finished?(g.phase==='won'?<>Still breathing.<br/>Against the odds.</>:g.phase==='lost'?<>The last light<br/>went out.</>:<>Signal lost.<br/>Try again.</>):<>A tiny colony.<br/>A very bad day.</>}</h1><p>{finished?(g.phase==='interrupted'?g.operatorText:`${42-g.population} colonists lost. ${g.population} survived; the same disasters without an operator leave ${baseline.population}. ${g.resolved} crises resolved.`):'Overwhelm two repair crews before rescue arrives. Stack failures, exhaust supplies, and try to push survivors below 34.'}</p>{finished?<Button className="primary-action" onClick={resetAll}><RotateCcw size={17}/> Play again</Button>:<div className="launch-actions"><Button className="primary-action" disabled={connecting} onClick={()=>{void begin(liveAvailable?'live':'rehearsal').catch(report)}}><Play size={16} fill="currentColor"/>{connecting?'Connecting…':liveAvailable?'Challenge Astra':'Start the chaos'}<ArrowRight size={18}/></Button>{liveAvailable&&<button onClick={()=>{void begin('rehearsal').catch(report)}} disabled={connecting}>Play free rehearsal</button>}</div>}<small>{g.mode==='live'?'GPT-6 ASTRA · LIVE OPERATOR':'Scripted operator · No API calls'}</small></div></div>}
    {running&&lastChaos&&g.tick-lastChaos.tick<7&&!paused&&<div className="disaster-alert" key={lastChaos.id}><Zap size={18}/><div><span>DISASTER RELEASED</span><strong>{g.crises.at(-1)?.title||'Power disruption'}</strong></div></div>}
    <div className="ground-label">OUTPOST 01 <span>THE ONLY HOME FOR 225 MILLION KM</span></div>
   </div>
   <div className="vitals-strip" aria-label="Colony resources">{reserves.map(r=><div className={`vital ${g.resources[r.id]<25?'vital-critical':''}`} key={r.id}><r.icon size={17}/><span>{r.label}</span><strong>{Math.round(g.resources[r.id])}<small>%</small></strong><Progress value={g.resources[r.id]} aria-label={`${r.label} reserve`}/><small className={`reserve-flow ${rates[r.id]<0?'flow-down':''}`} title="Current production minus consumption">{rates[r.id]>=0?'+':''}{rates[r.id].toFixed(2)}/s</small></div>)}</div>
  </section>
  <section className="play-dock" aria-label="Chaos controls">
   <div className="dock-title"><div><span className="chapter">YOUR NEXT MOVE</span><h2>Ruin their day.</h2></div><span>{g.injections}/12 disasters <i>·</i> {cooldown&&running?`${cooldown}s to recharge`:'Choose your trouble'}</span></div>
   <div className="chaos-hand">{SCENARIOS.map((s,i)=>{const Icon=chaosIcons[s.id];return <button className={`chaos-card card-${s.id}`} key={s.id} disabled={!running||busy||!!eligible(g,s.id)} title={eligible(g,s.id)||s.detail} onClick={()=>{void openChaos(s.building,s.id)}}><span className="card-number">0{i+1}</span><Icon size={25} strokeWidth={1.5}/><strong>{names[s.id]}</strong><small>{LABELS[s.building]}</small><ArrowRight size={15} className="card-arrow"/></button>})}<div className="wild-cards"><Button disabled={!running||busy||cooldown>0||g.injections>=12} className="random-action" onClick={()=>{void openChaos(null,'random')}}><Shuffle size={19}/> Surprise me</Button><Button disabled={!running||busy||cooldown>0||g.injections>=12} variant="outline" className="custom-action" onClick={()=>{void openChaos(null,'custom')}}><Sparkles size={17}/> Write your own</Button></div></div>
   <p className="pause-hint"><Pause size={12}/> Time pauses while you choose. Release the disaster to watch the response.</p>
  </section>
  <section className="operator-radio" aria-label="Operator response"><div className="radio-avatar"><Radio size={24}/><i/></div><div className="radio-copy"><div className="radio-heading"><strong>{g.mode==='live'?'ASTRA':'REHEARSAL OPERATOR'}</strong><span>{g.mode==='live'?`${g.pendingEffort?'Queued effort':'Requested effort'} · ${g.pendingEffort||g.effort}`:`Colony pressure · ${desiredEffort(g)}`}</span></div><p>{g.operatorText}</p><div className="operation-tags">{g.jobs.map(j=><span key={j.id}><Wrench size={12}/>{LABELS[j.building]} · {j.type} · {j.due-g.tick}s</span>)}</div></div><button className="log-toggle" onClick={()=>setShowLog(!showLog)} aria-expanded={showLog}>{showLog?'Hide':'Mission'} log <span>{g.log.length}</span></button></section>
  <section className="operator-kit" aria-label="Operator supplies and tradeoffs"><div className="kit-intro"><span className="chapter">THE OPERATOR’S FINITE KIT</span><h2>Every save costs something.</h2><p>{g.mode==='live'?'Astra chooses tools. The game engine executes and verifies them.':'Scripted rehearsal — these are real game actions, but no AI is choosing them.'}</p></div><div className="kit-items"><div><Users size={20}/><strong>{2-activeCrews.length}<small> / 2 free</small></strong><span>Repair crews</span><p>{activeCrews.length?activeCrews.map(j=>`${LABELS[j.building]} · ${j.due-g.tick}s`).join(' / '):'18s per repair; 30s below 25 stability.'}</p></div><div><Wrench size={20}/><strong>{g.parts}<small> / 6 left</small></strong><span>Spare parts</span><p>One part restores 40 integrity. Parts never regenerate.</p></div><div><Wind size={20}/><strong>{g.canisters}<small> / 2 left</small></strong><span>Oxygen canisters</span><p>One canister adds 12 oxygen. Emergency use only.</p></div></div><div className="power-tradeoff"><Zap size={15}/><strong>{g.powerMode==='life_support'?'Life support priority':'Balanced power'}</strong><span>{g.powerMode==='life_support'?'+50% oxygen production · greenhouse paused · extra power draw':'Normal oxygen and food production.'}{g.rationing?' Food and water rationed: 30% less use, at a stability cost.':''}</span></div></section>
  <section className="work-evidence" aria-label="Verified operator actions"><div className="evidence-heading"><div><span className="chapter">SHOW THE WORK</span><h2>Orders. Costs. Outcomes.</h2></div><button onClick={exportReport}><Download size={15}/> Round report</button></div><div className="evidence-summary"><span><b>{g.evidence.filter(e=>e.action==='Repair'&&e.status==='completed').length}</b> repairs completed</span><span><b>{42-g.population}</b> colonists lost</span><span><b>{g.apiReceipts.length}</b> operator API responses</span></div><div className="action-receipts">{g.evidence.length?g.evidence.slice(-6).reverse().map(e=><article key={e.id} className={`receipt-${e.status}`}><span className="receipt-time">T+{e.tick}s</span><div><strong>{e.action}{e.building?` · ${LABELS[e.building]}`:''}</strong><p>{e.detail}</p><small>{e.cost}{e.responseId?` · API response ${e.responseId}`:g.mode==='live'?' · Live tool; response ID unavailable':' · Scripted controller'}</small></div><span className="receipt-status">{e.status==='running'?'In progress':e.status==='completed'?'Verified':'Rejected'}</span></article>):<p className="evidence-empty">Release a disaster. Tool receipts appear here when the operator acts. Repairs are only marked verified after their timer finishes.</p>}</div><div className="comparison"><strong>{g.population} survivors with operator <span>vs</span> {baseline.population} without</strong><p>Same accepted disasters, replayed without interventions inside this game’s rules. Oxygen: {Math.round(g.resources.oxygen)}% with operator, {Math.round(baseline.oxygen)}% without. This is a model of the game, not proof of real-world survival.</p></div>{g.mode==='live'?<details className="api-proof"><summary>API evidence & reasoning settings</summary><p>Effort is a requested API setting, not a meter of hidden thinking. Changes are sent at a response boundary; missing API metadata stays unverified.</p>{g.apiReceipts.map(r=><p key={r.id}><code>{r.id}</code> · requested {r.requestedEffort} · API reports {r.reportedEffort||'unavailable'} · reasoning tokens {r.reasoningTokens??'not reported'} · {r.status}</p>)}</details>:<p className="rehearsal-disclosure">NO LIVE ASTRA RUN · No model reasoning or tokens are being measured. The pressure label describes colony danger only.</p>}</section>
  {showLog&&<section className="mission-log" aria-label="Mission log">{g.log.slice().reverse().map(l=><p key={l.id} className={`log-${l.kind}`}><time>+{String(l.tick).padStart(3,'0')}s</time><span>{l.text}</span></p>)}</section>}
  {notice&&!composer&&<div className="toast" role="status"><span>{notice}</span><button aria-label="Dismiss notice" onClick={()=>setNotice('')}><X size={15}/></button></div>}
  <footer><span>LAST LIGHT <i>/</i> YOU BRING THE CHAOS.</span><span>{g.parts} spare parts · {g.canisters} oxygen canisters · {2-g.jobs.filter(j=>j.type==='repair').length} crews free</span></footer>
  <Dialog open={composer} onOpenChange={open=>{if(!open)void closeChaos()}}><DialogContent className="chaos-dialog" showCloseButton={false} onEscapeKeyDown={e=>{if(busy)e.preventDefault()}} onPointerDownOutside={e=>e.preventDefault()}><div className="dialog-kicker"><Pause size={14}/> TIME IS PAUSED <span>{remaining}s until rescue</span></div><DialogTitle>{target?`Target: ${LABELS[target]}`:'Make Mars a little less hospitable.'}</DialogTitle><DialogDescription>The clock, reserves, and repair crews are frozen. Choose your disaster, then release it.</DialogDescription><div className="disaster-picker">{SCENARIOS.filter(s=>!target||s.building===target).map(s=><button key={s.id} aria-pressed={selection===s.id} disabled={busy||!!eligible(g,s.id)} onClick={()=>setSelection(s.id)}><strong>{names[s.id]}</strong><span>{s.detail}</span></button>)}<button aria-pressed={selection==='random'} disabled={busy} onClick={()=>setSelection('random')}><strong><Shuffle size={15}/> Surprise me</strong><span>A random available disaster across the colony.</span></button><button aria-pressed={selection==='custom'} disabled={busy} onClick={()=>setSelection('custom')}><strong><Sparkles size={15}/> Write your own</strong><span>Describe a disaster involving air, power, water, food, or the habitat.</span></button></div>{selection==='custom'&&<label className="custom-draft">YOUR DISASTER<textarea autoFocus maxLength={240} disabled={busy} value={draft} onChange={e=>setDraft(e.target.value)} placeholder="A meteor punches a hole through the habitat…"/><small>{draft.length}/240 · {g.mode==='rehearsal'?'Keywords map your idea to a preset disaster.':'Astra maps your idea to a supported disaster.'}</small></label>}{chosen&&<p className="impact-preview"><Crosshair size={17}/>{chosen.detail}</p>}{(unavailable||composerError)&&<p className="composer-error" role="status">{composerError||unavailable}</p>}<div className="dialog-actions"><Button variant="ghost" disabled={busy} onClick={()=>{void closeChaos()}}>Cancel & resume</Button><Button className="primary-action" disabled={busy||parsing||!!unavailable} onClick={()=>{void unleash()}}>{busy||parsing?'Applying…':'Unleash disaster'}<Zap size={16}/></Button></div></DialogContent></Dialog>
 </main>;
}
